[tools]
actionlint = "latest"
bun = "latest"
dotnet = "latest"
gitleaks = "latest"
go = "latest"
helm = "latest"
java = "latest"
jq = "latest"
kubectl = "latest"
markdownlint-cli2 = "latest"
node = "26"
pipx = "latest"
pnpm = "latest"
pre-commit = "latest"
prettier = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
terraform = "latest"
yamllint = "latest"
yarn = "latest"
yq = "latest"
bitwarden-secrets-manager = "latest"
buf = "latest"

